def generate_random_names():
    return [
        "oldoc",
        "black",
        "home_office",
        "holly",
        "Holley01",
        "myoffice",
        "2020",
        "firstPerson",
        "FirstName",
        "katrin",
        "united",
        "meuIf",
        "hame",
        "upload",
        "Merson",
        "mersia",
        "otis",
        "Heynam",
        "reio",
        "lucky",
        "rimuru",
        "grumer",
    ]
